[package]
name = "mandelbrot_mpi_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mandelbrot_seq"
path = "src/bin/mandelbrot_seq.rs"

[[bin]]
name = "mandelbrot_mpi"
path = "src/bin/mandelbrot_mpi.rs"

[dependencies]
mpi = "0.6"
image = "0.24"
num-complex = "0.4"

